version: '3'

services:
  db:
      image: 'mysql:5.7'
      command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: app
          MYSQL_USER: app
          MYSQL_PASSWORD: secret
      ports:
        - '3306:3306'
      volumes:
        - db_data:/var/lib/mysql:rw

  adminer:
    image: adminer
    ports:
      - 7000:8080

volumes:
  db_data:
