version: '3'

services:
  db:
      image: 'mysql:5.7'
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: my_app
          MYSQL_USER: my_app
          MYSQL_PASSWORD: secret
      ports:
        - '3306:3306'
      volumes:
        - db_data:/var/lib/mysql:rw

  adminer:
    image: adminer
    ports:
      - 7000:8080

  sandbox:
    image: 'oxheadalpha/flextesa:20230502'
    command: mumbaibox start
    ports:
      - '20000:20000'

volumes:
  db_data:
