security:
    enable_authenticator_manager: true
    providers:
        members:
          entity:
            class: App\Entity\Member
            property: address

    firewalls:
        main:
            custom_authenticator:
                - App\Security\TezosAuthenticator
            entry_point: form_login
            pattern: ^/
            lazy: true
            form_login:
                login_path: /
            logout:
                path: app_logout

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/member-area, roles: ROLE_MEMBER }
